"""Baseline migration

Revision ID: 08a47448b137
Revises: 
Create Date: 2026-07-26 13:04:47.773466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08a47448b137'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ats_health_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('ats_type', sa.String(), nullable=True),
    sa.Column('is_success', sa.Boolean(), nullable=True),
    sa.Column('jobs_collected', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('run_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ats_health_log_company_name'), 'ats_health_log', ['company_name'], unique=False)
    op.create_index(op.f('ix_ats_health_log_id'), 'ats_health_log', ['id'], unique=False)
    op.create_table('career_insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('insight_type', sa.String(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_insights_id'), 'career_insights', ['id'], unique=False)
    op.create_table('certifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('is_free', sa.Boolean(), nullable=True),
    sa.Column('cost', sa.String(), nullable=True),
    sa.Column('difficulty', sa.String(), nullable=True),
    sa.Column('estimated_hours', sa.Integer(), nullable=True),
    sa.Column('validity_years', sa.Integer(), nullable=True),
    sa.Column('exam_required', sa.Boolean(), nullable=True),
    sa.Column('skills_covered', sa.JSON(), nullable=True),
    sa.Column('roles', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('availability_status', sa.String(), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('price_inr', sa.Integer(), nullable=True),
    sa.Column('affordability', sa.String(), nullable=True),
    sa.Column('free_learning_available', sa.Boolean(), nullable=True),
    sa.Column('financial_aid_available', sa.Boolean(), nullable=True),
    sa.Column('student_discount_available', sa.Boolean(), nullable=True),
    sa.Column('certification_type', sa.String(), nullable=True),
    sa.Column('verification_source', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_certifications_id'), 'certifications', ['id'], unique=False)
    op.create_table('collector_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collector_name', sa.String(), nullable=True),
    sa.Column('ats_type', sa.String(), nullable=True),
    sa.Column('alert_type', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('metric_name', sa.String(), nullable=True),
    sa.Column('metric_value', sa.Float(), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collector_alerts_alert_type'), 'collector_alerts', ['alert_type'], unique=False)
    op.create_index(op.f('ix_collector_alerts_collector_name'), 'collector_alerts', ['collector_name'], unique=False)
    op.create_index(op.f('ix_collector_alerts_created_at'), 'collector_alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_collector_alerts_id'), 'collector_alerts', ['id'], unique=False)
    op.create_table('collector_failures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collector_name', sa.String(), nullable=True),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(), nullable=True),
    sa.Column('last_attempt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collector_failures_collector_name'), 'collector_failures', ['collector_name'], unique=False)
    op.create_index(op.f('ix_collector_failures_id'), 'collector_failures', ['id'], unique=False)
    op.create_table('collector_health',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collector_name', sa.String(), nullable=True),
    sa.Column('ats_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('collector_score', sa.Float(), nullable=True),
    sa.Column('collector_stability', sa.Float(), nullable=True),
    sa.Column('roi_tier', sa.String(), nullable=True),
    sa.Column('adaptive_interval_hours', sa.Float(), nullable=True),
    sa.Column('jobs_collected_today', sa.Integer(), nullable=True),
    sa.Column('jobs_collected_total', sa.Integer(), nullable=True),
    sa.Column('jobs_inserted', sa.Integer(), nullable=True),
    sa.Column('active_jobs', sa.Integer(), nullable=True),
    sa.Column('new_jobs_pct', sa.Float(), nullable=True),
    sa.Column('update_rate', sa.Float(), nullable=True),
    sa.Column('duplicates_removed', sa.Integer(), nullable=True),
    sa.Column('duplicate_pct', sa.Float(), nullable=True),
    sa.Column('broken_links_pct', sa.Float(), nullable=True),
    sa.Column('expired_pct', sa.Float(), nullable=True),
    sa.Column('avg_confidence', sa.Float(), nullable=True),
    sa.Column('avg_completeness', sa.Float(), nullable=True),
    sa.Column('avg_freshness_days', sa.Float(), nullable=True),
    sa.Column('avg_verification_success', sa.Float(), nullable=True),
    sa.Column('apply_ctr', sa.Float(), nullable=True),
    sa.Column('salary_change_rate', sa.Float(), nullable=True),
    sa.Column('history_events_generated', sa.Integer(), nullable=True),
    sa.Column('success_rate', sa.Float(), nullable=True),
    sa.Column('average_runtime_ms', sa.Float(), nullable=True),
    sa.Column('avg_response_ms', sa.Float(), nullable=True),
    sa.Column('crawler_uptime_pct', sa.Float(), nullable=True),
    sa.Column('timeout_rate', sa.Float(), nullable=True),
    sa.Column('retry_success_rate', sa.Float(), nullable=True),
    sa.Column('yield_percent', sa.Float(), nullable=True),
    sa.Column('last_run', sa.DateTime(), nullable=True),
    sa.Column('last_success', sa.DateTime(), nullable=True),
    sa.Column('last_failure', sa.DateTime(), nullable=True),
    sa.Column('success_count', sa.Integer(), nullable=True),
    sa.Column('failure_count', sa.Integer(), nullable=True),
    sa.Column('errors', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collector_health_ats_type'), 'collector_health', ['ats_type'], unique=False)
    op.create_index(op.f('ix_collector_health_collector_name'), 'collector_health', ['collector_name'], unique=True)
    op.create_index(op.f('ix_collector_health_collector_score'), 'collector_health', ['collector_score'], unique=False)
    op.create_index(op.f('ix_collector_health_id'), 'collector_health', ['id'], unique=False)
    op.create_index(op.f('ix_collector_health_roi_tier'), 'collector_health', ['roi_tier'], unique=False)
    op.create_table('collector_health_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collector_name', sa.String(), nullable=True),
    sa.Column('ats_type', sa.String(), nullable=True),
    sa.Column('snapshot_date', sa.DateTime(), nullable=True),
    sa.Column('collector_score', sa.Float(), nullable=True),
    sa.Column('collector_stability', sa.Float(), nullable=True),
    sa.Column('roi_tier', sa.String(), nullable=True),
    sa.Column('jobs_collected', sa.Integer(), nullable=True),
    sa.Column('active_jobs', sa.Integer(), nullable=True),
    sa.Column('duplicate_pct', sa.Float(), nullable=True),
    sa.Column('broken_links_pct', sa.Float(), nullable=True),
    sa.Column('avg_confidence', sa.Float(), nullable=True),
    sa.Column('avg_freshness_days', sa.Float(), nullable=True),
    sa.Column('success_rate', sa.Float(), nullable=True),
    sa.Column('crawler_uptime_pct', sa.Float(), nullable=True),
    sa.Column('avg_response_ms', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collector_health_history_collector_name'), 'collector_health_history', ['collector_name'], unique=False)
    op.create_index(op.f('ix_collector_health_history_id'), 'collector_health_history', ['id'], unique=False)
    op.create_index(op.f('ix_collector_health_history_snapshot_date'), 'collector_health_history', ['snapshot_date'], unique=False)
    op.create_table('company_registry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('company_category', sa.String(), nullable=True),
    sa.Column('hiring_in_india', sa.Boolean(), nullable=True),
    sa.Column('india_hiring_priority', sa.Integer(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.Column('ats_type', sa.String(), nullable=True),
    sa.Column('ats_identifier', sa.String(), nullable=True),
    sa.Column('workday_tenant', sa.String(), nullable=True),
    sa.Column('workday_site_url', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('validation_status', sa.String(), nullable=True),
    sa.Column('last_checked', sa.DateTime(), nullable=True),
    sa.Column('confidence_score', sa.Integer(), nullable=True),
    sa.Column('active_jobs', sa.Integer(), nullable=True),
    sa.Column('india_jobs_found', sa.Integer(), nullable=True),
    sa.Column('collector_enabled', sa.Boolean(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('company_size', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('collector', sa.String(), nullable=True),
    sa.Column('crawl_frequency', sa.String(), nullable=True),
    sa.Column('total_jobs_ever', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('failure_count', sa.Integer(), nullable=True),
    sa.Column('retry_interval_minutes', sa.Integer(), nullable=True),
    sa.Column('last_success', sa.DateTime(), nullable=True),
    sa.Column('health_score', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_registry_company_name'), 'company_registry', ['company_name'], unique=True)
    op.create_index(op.f('ix_company_registry_id'), 'company_registry', ['id'], unique=False)
    op.create_table('dashboard_stats_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_jobs', sa.Integer(), nullable=True),
    sa.Column('active_jobs', sa.Integer(), nullable=True),
    sa.Column('verified_jobs', sa.Integer(), nullable=True),
    sa.Column('remote_jobs', sa.Integer(), nullable=True),
    sa.Column('freshers_jobs', sa.Integer(), nullable=True),
    sa.Column('internships', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dashboard_stats_cache_id'), 'dashboard_stats_cache', ['id'], unique=False)
    op.create_table('discovered_company_ats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('career_url', sa.String(), nullable=True),
    sa.Column('redirect_url', sa.String(), nullable=True),
    sa.Column('ats_type', sa.String(), nullable=True),
    sa.Column('ats_version', sa.String(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('detection_method', sa.String(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('auto_discovered', sa.Boolean(), nullable=True),
    sa.Column('last_success', sa.DateTime(), nullable=True),
    sa.Column('last_failure', sa.DateTime(), nullable=True),
    sa.Column('collector_assigned', sa.String(), nullable=True),
    sa.Column('last_checked', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discovered_company_ats_company_name'), 'discovered_company_ats', ['company_name'], unique=True)
    op.create_index(op.f('ix_discovered_company_ats_id'), 'discovered_company_ats', ['id'], unique=False)
    op.create_table('hiring_intelligence_company_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('snapshot_date', sa.DateTime(), nullable=True),
    sa.Column('jobs_today', sa.Integer(), nullable=True),
    sa.Column('jobs_this_week', sa.Integer(), nullable=True),
    sa.Column('hiring_velocity', sa.String(), nullable=True),
    sa.Column('hiring_trend', sa.String(), nullable=True),
    sa.Column('company_hiring_score', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hiring_intelligence_company_snapshots_company_name'), 'hiring_intelligence_company_snapshots', ['company_name'], unique=False)
    op.create_index(op.f('ix_hiring_intelligence_company_snapshots_id'), 'hiring_intelligence_company_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_hiring_intelligence_company_snapshots_snapshot_date'), 'hiring_intelligence_company_snapshots', ['snapshot_date'], unique=False)
    op.create_table('hiring_intelligence_global_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.DateTime(), nullable=True),
    sa.Column('jobs_today', sa.Integer(), nullable=True),
    sa.Column('jobs_this_week', sa.Integer(), nullable=True),
    sa.Column('jobs_this_month', sa.Integer(), nullable=True),
    sa.Column('expired_today', sa.Integer(), nullable=True),
    sa.Column('broken_today', sa.Integer(), nullable=True),
    sa.Column('recovered_today', sa.Integer(), nullable=True),
    sa.Column('average_confidence', sa.Integer(), nullable=True),
    sa.Column('average_freshness', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hiring_intelligence_global_snapshots_id'), 'hiring_intelligence_global_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_hiring_intelligence_global_snapshots_snapshot_date'), 'hiring_intelligence_global_snapshots', ['snapshot_date'], unique=False)
    op.create_table('job_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('is_official', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('health_score', sa.Integer(), nullable=True),
    sa.Column('last_success', sa.DateTime(), nullable=True),
    sa.Column('last_failure', sa.DateTime(), nullable=True),
    sa.Column('failure_count', sa.Integer(), nullable=True),
    sa.Column('success_count', sa.Integer(), nullable=True),
    sa.Column('average_response_time', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_sources_health_score'), 'job_sources', ['health_score'], unique=False)
    op.create_index(op.f('ix_job_sources_id'), 'job_sources', ['id'], unique=False)
    op.create_index(op.f('ix_job_sources_source_name'), 'job_sources', ['source_name'], unique=True)
    op.create_index(op.f('ix_job_sources_success_count'), 'job_sources', ['success_count'], unique=False)
    op.create_table('learning_resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('difficulty', sa.String(), nullable=True),
    sa.Column('duration', sa.String(), nullable=True),
    sa.Column('is_free', sa.Boolean(), nullable=True),
    sa.Column('skills_covered', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('channel', sa.String(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('last_verified', sa.DateTime(), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=True),
    sa.Column('availability_status', sa.String(), nullable=True),
    sa.Column('affordability', sa.String(), nullable=True),
    sa.Column('price', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('roles', sa.JSON(), nullable=True),
    sa.Column('verification_source', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_resources_id'), 'learning_resources', ['id'], unique=False)
    op.create_table('normalized_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_value', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('is_tier1_city', sa.Boolean(), nullable=True),
    sa.Column('is_tier2_city', sa.Boolean(), nullable=True),
    sa.Column('is_metro', sa.Boolean(), nullable=True),
    sa.Column('cost_of_living_index', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_normalized_locations_city'), 'normalized_locations', ['city'], unique=False)
    op.create_index(op.f('ix_normalized_locations_id'), 'normalized_locations', ['id'], unique=False)
    op.create_index(op.f('ix_normalized_locations_raw_value'), 'normalized_locations', ['raw_value'], unique=True)
    op.create_table('opportunities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('job_type', sa.String(), nullable=True),
    sa.Column('opportunity_category', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('trust_score', sa.Integer(), nullable=True),
    sa.Column('salary_range', sa.String(), nullable=True),
    sa.Column('apply_url', sa.String(), nullable=True),
    sa.Column('posted_date', sa.DateTime(), nullable=True),
    sa.Column('computed_rank_score', sa.Integer(), nullable=True),
    sa.Column('opportunity_hash', sa.String(), nullable=True),
    sa.Column('primary_source', sa.String(), nullable=True),
    sa.Column('source_trust_score', sa.Integer(), nullable=True),
    sa.Column('last_checked', sa.DateTime(), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('ats_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('apply_url_status', sa.String(), nullable=True),
    sa.Column('link_classification', sa.String(), nullable=True),
    sa.Column('link_quality_score', sa.Integer(), nullable=True),
    sa.Column('verified_apply_url', sa.String(), nullable=True),
    sa.Column('source_job_id', sa.String(), nullable=True),
    sa.Column('last_url_verified_at', sa.DateTime(), nullable=True),
    sa.Column('apply_attempts', sa.Integer(), nullable=True),
    sa.Column('apply_success', sa.Integer(), nullable=True),
    sa.Column('apply_failure', sa.Integer(), nullable=True),
    sa.Column('homepage_redirects', sa.Integer(), nullable=True),
    sa.Column('expired_clicks', sa.Integer(), nullable=True),
    sa.Column('is_india_job', sa.Boolean(), nullable=True),
    sa.Column('india_relevance_score', sa.Integer(), nullable=True),
    sa.Column('india_confidence_score', sa.Integer(), nullable=True),
    sa.Column('required_skills', sa.Text(), nullable=True),
    sa.Column('collected_by', sa.String(), nullable=True),
    sa.Column('legacy_hash', sa.String(), nullable=True),
    sa.Column('lifecycle_status', sa.String(), nullable=True),
    sa.Column('verification_count', sa.Integer(), nullable=True),
    sa.Column('expired_reason', sa.String(), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(), nullable=True),
    sa.Column('confidence_score', sa.Integer(), nullable=True),
    sa.Column('completeness_score', sa.Integer(), nullable=True),
    sa.Column('salary_min', sa.Integer(), nullable=True),
    sa.Column('salary_max', sa.Integer(), nullable=True),
    sa.Column('salary_currency', sa.String(), nullable=True),
    sa.Column('salary_period', sa.String(), nullable=True),
    sa.Column('experience_min', sa.Integer(), nullable=True),
    sa.Column('experience_max', sa.Integer(), nullable=True),
    sa.Column('fresher_friendly', sa.Boolean(), nullable=True),
    sa.Column('campus_hiring', sa.Boolean(), nullable=True),
    sa.Column('walk_in_drive', sa.Boolean(), nullable=True),
    sa.Column('mass_hiring', sa.Boolean(), nullable=True),
    sa.Column('internship_type', sa.String(), nullable=True),
    sa.Column('work_mode', sa.String(), nullable=True),
    sa.Column('duration_months', sa.Integer(), nullable=True),
    sa.Column('stipend_min', sa.String(), nullable=True),
    sa.Column('stipend_max', sa.String(), nullable=True),
    sa.Column('ppo_available', sa.Boolean(), nullable=True),
    sa.Column('eligibility_batch', sa.String(), nullable=True),
    sa.Column('application_deadline', sa.DateTime(), nullable=True),
    sa.Column('minimum_cgpa', sa.Float(), nullable=True),
    sa.Column('allowed_degrees', sa.String(), nullable=True),
    sa.Column('allowed_branches', sa.String(), nullable=True),
    sa.Column('backlogs_allowed', sa.Boolean(), nullable=True),
    sa.Column('year_of_passing', sa.String(), nullable=True),
    sa.Column('bond_period', sa.String(), nullable=True),
    sa.Column('relocation_required', sa.Boolean(), nullable=True),
    sa.Column('service_agreement', sa.Boolean(), nullable=True),
    sa.Column('selection_rounds', sa.JSON(), nullable=True),
    sa.Column('expected_round_count', sa.Integer(), nullable=True),
    sa.Column('difficulty_level', sa.String(), nullable=True),
    sa.Column('times_verified', sa.Integer(), nullable=True),
    sa.Column('times_updated', sa.Integer(), nullable=True),
    sa.Column('times_reactivated', sa.Integer(), nullable=True),
    sa.Column('change_score', sa.Integer(), nullable=True),
    sa.Column('description_hash', sa.String(), nullable=True),
    sa.Column('skills_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunities_apply_url_status'), 'opportunities', ['apply_url_status'], unique=False)
    op.create_index(op.f('ix_opportunities_change_score'), 'opportunities', ['change_score'], unique=False)
    op.create_index(op.f('ix_opportunities_company'), 'opportunities', ['company'], unique=False)
    op.create_index(op.f('ix_opportunities_completeness_score'), 'opportunities', ['completeness_score'], unique=False)
    op.create_index(op.f('ix_opportunities_computed_rank_score'), 'opportunities', ['computed_rank_score'], unique=False)
    op.create_index(op.f('ix_opportunities_confidence_score'), 'opportunities', ['confidence_score'], unique=False)
    op.create_index(op.f('ix_opportunities_id'), 'opportunities', ['id'], unique=False)
    op.create_index(op.f('ix_opportunities_india_confidence_score'), 'opportunities', ['india_confidence_score'], unique=False)
    op.create_index(op.f('ix_opportunities_india_relevance_score'), 'opportunities', ['india_relevance_score'], unique=False)
    op.create_index(op.f('ix_opportunities_is_india_job'), 'opportunities', ['is_india_job'], unique=False)
    op.create_index(op.f('ix_opportunities_last_verified_at'), 'opportunities', ['last_verified_at'], unique=False)
    op.create_index(op.f('ix_opportunities_legacy_hash'), 'opportunities', ['legacy_hash'], unique=False)
    op.create_index(op.f('ix_opportunities_lifecycle_status'), 'opportunities', ['lifecycle_status'], unique=False)
    op.create_index(op.f('ix_opportunities_link_quality_score'), 'opportunities', ['link_quality_score'], unique=False)
    op.create_index(op.f('ix_opportunities_location'), 'opportunities', ['location'], unique=False)
    op.create_index(op.f('ix_opportunities_opportunity_category'), 'opportunities', ['opportunity_category'], unique=False)
    op.create_index(op.f('ix_opportunities_opportunity_hash'), 'opportunities', ['opportunity_hash'], unique=False)
    op.create_index(op.f('ix_opportunities_title'), 'opportunities', ['title'], unique=False)
    op.create_table('pipeline_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pipeline_name', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('records_collected', sa.Integer(), nullable=True),
    sa.Column('records_cleaned', sa.Integer(), nullable=True),
    sa.Column('records_inserted', sa.Integer(), nullable=True),
    sa.Column('records_deduplicated', sa.Integer(), nullable=True),
    sa.Column('errors', sa.JSON(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_runs_id'), 'pipeline_runs', ['id'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_pipeline_name'), 'pipeline_runs', ['pipeline_name'], unique=False)
    op.create_table('raw_internships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('duration', sa.String(), nullable=True),
    sa.Column('stipend', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('apply_url', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('raw_data', sa.Text(), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_internships_id'), 'raw_internships', ['id'], unique=False)
    op.create_table('raw_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('job_type', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('salary_range', sa.String(), nullable=True),
    sa.Column('apply_url', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('ats_type', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('raw_data', sa.Text(), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_jobs_id'), 'raw_jobs', ['id'], unique=False)
    op.create_table('role_skill_maps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('skill', sa.String(), nullable=True),
    sa.Column('importance', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_skill_maps_id'), 'role_skill_maps', ['id'], unique=False)
    op.create_index(op.f('ix_role_skill_maps_role'), 'role_skill_maps', ['role'], unique=False)
    op.create_index(op.f('ix_role_skill_maps_skill'), 'role_skill_maps', ['skill'], unique=False)
    op.create_table('search_aggregates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query_text', sa.String(), nullable=True),
    sa.Column('total_searches', sa.Integer(), nullable=True),
    sa.Column('zero_result_rate', sa.Float(), nullable=True),
    sa.Column('ctr', sa.Float(), nullable=True),
    sa.Column('avg_click_position', sa.Float(), nullable=True),
    sa.Column('avg_session_duration', sa.Float(), nullable=True),
    sa.Column('last_searched_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_aggregates_id'), 'search_aggregates', ['id'], unique=False)
    op.create_index(op.f('ix_search_aggregates_last_searched_at'), 'search_aggregates', ['last_searched_at'], unique=False)
    op.create_index(op.f('ix_search_aggregates_query_text'), 'search_aggregates', ['query_text'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('verification_token', sa.String(), nullable=True),
    sa.Column('verification_expires', sa.DateTime(), nullable=True),
    sa.Column('reset_token', sa.String(), nullable=True),
    sa.Column('reset_expires', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_reset_token'), 'users', ['reset_token'], unique=False)
    op.create_index(op.f('ix_users_verification_token'), 'users', ['verification_token'], unique=False)
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('opportunity_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('applied_date', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_id'), 'applications', ['id'], unique=False)
    op.create_table('career_readiness',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('target_role', sa.String(), nullable=True),
    sa.Column('readiness_score', sa.Integer(), nullable=True),
    sa.Column('missing_skills', sa.JSON(), nullable=True),
    sa.Column('recommended_skills', sa.JSON(), nullable=True),
    sa.Column('estimated_months', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_readiness_id'), 'career_readiness', ['id'], unique=False)
    op.create_index(op.f('ix_career_readiness_target_role'), 'career_readiness', ['target_role'], unique=False)
    op.create_index(op.f('ix_career_readiness_user_id'), 'career_readiness', ['user_id'], unique=False)
    op.create_table('career_readiness_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('target_role', sa.String(), nullable=True),
    sa.Column('readiness_score', sa.Integer(), nullable=True),
    sa.Column('skill_coverage_score', sa.Integer(), nullable=True),
    sa.Column('experience_score', sa.Integer(), nullable=True),
    sa.Column('resume_score', sa.Integer(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_readiness_snapshots_id'), 'career_readiness_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_career_readiness_snapshots_target_role'), 'career_readiness_snapshots', ['target_role'], unique=False)
    op.create_index(op.f('ix_career_readiness_snapshots_user_id'), 'career_readiness_snapshots', ['user_id'], unique=False)
    op.create_table('collection_lineage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('collector_name', sa.String(), nullable=True),
    sa.Column('collector_version', sa.String(), nullable=True),
    sa.Column('collection_time', sa.DateTime(), nullable=True),
    sa.Column('parser_version', sa.String(), nullable=True),
    sa.Column('verification_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_lineage_id'), 'collection_lineage', ['id'], unique=False)
    op.create_table('job_match_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('opportunity_id', sa.Integer(), nullable=True),
    sa.Column('match_score', sa.Integer(), nullable=True),
    sa.Column('skill_score', sa.Integer(), nullable=True),
    sa.Column('role_score', sa.Integer(), nullable=True),
    sa.Column('location_score', sa.Integer(), nullable=True),
    sa.Column('freshness_score', sa.Integer(), nullable=True),
    sa.Column('company_score', sa.Integer(), nullable=True),
    sa.Column('salary_score', sa.Integer(), nullable=True),
    sa.Column('matching_skills', sa.JSON(), nullable=True),
    sa.Column('missing_skills', sa.JSON(), nullable=True),
    sa.Column('match_level', sa.String(), nullable=True),
    sa.Column('explanation', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_match_scores_id'), 'job_match_scores', ['id'], unique=False)
    op.create_table('job_quality_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=True),
    sa.Column('quality_score', sa.Integer(), nullable=True),
    sa.Column('trust_score', sa.Integer(), nullable=True),
    sa.Column('verification_status', sa.String(), nullable=True),
    sa.Column('is_duplicate', sa.Boolean(), nullable=True),
    sa.Column('is_official', sa.Boolean(), nullable=True),
    sa.Column('salary_confidence', sa.Integer(), nullable=True),
    sa.Column('last_verified', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_quality_metrics_id'), 'job_quality_metrics', ['id'], unique=False)
    op.create_table('opportunity_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('changed_field', sa.String(), nullable=True),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('change_summary', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('confidence_before', sa.Integer(), nullable=True),
    sa.Column('confidence_after', sa.Integer(), nullable=True),
    sa.Column('completeness_before', sa.Integer(), nullable=True),
    sa.Column('completeness_after', sa.Integer(), nullable=True),
    sa.Column('link_quality_before', sa.Integer(), nullable=True),
    sa.Column('link_quality_after', sa.Integer(), nullable=True),
    sa.Column('lifecycle_before', sa.String(), nullable=True),
    sa.Column('lifecycle_after', sa.String(), nullable=True),
    sa.Column('collector_name', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('detected_by', sa.String(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunity_history_changed_field'), 'opportunity_history', ['changed_field'], unique=False)
    op.create_index(op.f('ix_opportunity_history_event_type'), 'opportunity_history', ['event_type'], unique=False)
    op.create_index(op.f('ix_opportunity_history_id'), 'opportunity_history', ['id'], unique=False)
    op.create_index(op.f('ix_opportunity_history_opportunity_id'), 'opportunity_history', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_opportunity_history_recorded_at'), 'opportunity_history', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_opportunity_history_severity'), 'opportunity_history', ['severity'], unique=False)
    op.create_table('opportunity_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=True),
    sa.Column('source_name', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('trust_score', sa.Integer(), nullable=True),
    sa.Column('last_checked', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunity_sources_id'), 'opportunity_sources', ['id'], unique=False)
    op.create_table('resume_match_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('opportunity_id', sa.Integer(), nullable=True),
    sa.Column('match_percentage', sa.Integer(), nullable=True),
    sa.Column('missing_skills', sa.JSON(), nullable=True),
    sa.Column('matched_skills', sa.JSON(), nullable=True),
    sa.Column('recommended_skills', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_match_results_id'), 'resume_match_results', ['id'], unique=False)
    op.create_index(op.f('ix_resume_match_results_opportunity_id'), 'resume_match_results', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_resume_match_results_user_id'), 'resume_match_results', ['user_id'], unique=False)
    op.create_table('resume_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_file', sa.String(), nullable=True),
    sa.Column('extracted_skills', sa.JSON(), nullable=True),
    sa.Column('extracted_projects', sa.JSON(), nullable=True),
    sa.Column('extracted_education', sa.JSON(), nullable=True),
    sa.Column('extracted_certifications', sa.JSON(), nullable=True),
    sa.Column('extracted_experience', sa.JSON(), nullable=True),
    sa.Column('ats_score', sa.Integer(), nullable=True),
    sa.Column('strengths', sa.JSON(), nullable=True),
    sa.Column('weaknesses', sa.JSON(), nullable=True),
    sa.Column('suggestions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_profiles_id'), 'resume_profiles', ['id'], unique=False)
    op.create_table('resumes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('ats_score', sa.Integer(), nullable=True),
    sa.Column('skills_score', sa.Integer(), nullable=True),
    sa.Column('missing_skills', sa.String(), nullable=True),
    sa.Column('posted_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resumes_id'), 'resumes', ['id'], unique=False)
    op.create_table('search_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('query', sa.String(), nullable=True),
    sa.Column('clicked_job_id', sa.Integer(), nullable=True),
    sa.Column('result_count', sa.Integer(), nullable=True),
    sa.Column('click_position', sa.Integer(), nullable=True),
    sa.Column('is_zero_results', sa.Boolean(), nullable=True),
    sa.Column('response_time_ms', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['clicked_job_id'], ['opportunities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_analytics_created_at'), 'search_analytics', ['created_at'], unique=False)
    op.create_index(op.f('ix_search_analytics_id'), 'search_analytics', ['id'], unique=False)
    op.create_index(op.f('ix_search_analytics_query'), 'search_analytics', ['query'], unique=False)
    op.create_table('search_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('query_text', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('job_type', sa.String(), nullable=True),
    sa.Column('result_count', sa.Integer(), nullable=True),
    sa.Column('clicked_job_id', sa.Integer(), nullable=True),
    sa.Column('click_position', sa.Integer(), nullable=True),
    sa.Column('ignored_job_ids', sa.JSON(), nullable=True),
    sa.Column('session_duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['clicked_job_id'], ['opportunities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_events_created_at'), 'search_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_search_events_id'), 'search_events', ['id'], unique=False)
    op.create_index(op.f('ix_search_events_query_text'), 'search_events', ['query_text'], unique=False)
    op.create_index(op.f('ix_search_events_user_id'), 'search_events', ['user_id'], unique=False)
    op.create_table('search_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('query', sa.String(), nullable=True),
    sa.Column('results_count', sa.Integer(), nullable=True),
    sa.Column('clicked_job_id', sa.Integer(), nullable=True),
    sa.Column('click_position', sa.Integer(), nullable=True),
    sa.Column('filters_used', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_logs_id'), 'search_logs', ['id'], unique=False)
    op.create_index(op.f('ix_search_logs_query'), 'search_logs', ['query'], unique=False)
    op.create_table('user_career_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('target_role', sa.String(), nullable=True),
    sa.Column('experience_level', sa.String(), nullable=True),
    sa.Column('current_role', sa.String(), nullable=True),
    sa.Column('education', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_career_profiles_id'), 'user_career_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_user_career_profiles_user_id'), 'user_career_profiles', ['user_id'], unique=True)
    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('preferred_roles', sa.JSON(), nullable=True),
    sa.Column('preferred_locations', sa.JSON(), nullable=True),
    sa.Column('preferred_job_type', sa.JSON(), nullable=True),
    sa.Column('remote_preference', sa.String(), nullable=True),
    sa.Column('minimum_salary', sa.Integer(), nullable=True),
    sa.Column('preferred_companies', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_preferences_id'), 'user_preferences', ['id'], unique=False)
    op.create_table('user_skill_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('skill_name', sa.String(), nullable=True),
    sa.Column('proficiency_level', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_skill_profiles_id'), 'user_skill_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_user_skill_profiles_skill_name'), 'user_skill_profiles', ['skill_name'], unique=False)
    op.create_index(op.f('ix_user_skill_profiles_user_id'), 'user_skill_profiles', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_skill_profiles_user_id'), table_name='user_skill_profiles')
    op.drop_index(op.f('ix_user_skill_profiles_skill_name'), table_name='user_skill_profiles')
    op.drop_index(op.f('ix_user_skill_profiles_id'), table_name='user_skill_profiles')
    op.drop_table('user_skill_profiles')
    op.drop_index(op.f('ix_user_preferences_id'), table_name='user_preferences')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_user_career_profiles_user_id'), table_name='user_career_profiles')
    op.drop_index(op.f('ix_user_career_profiles_id'), table_name='user_career_profiles')
    op.drop_table('user_career_profiles')
    op.drop_index(op.f('ix_search_logs_query'), table_name='search_logs')
    op.drop_index(op.f('ix_search_logs_id'), table_name='search_logs')
    op.drop_table('search_logs')
    op.drop_index(op.f('ix_search_events_user_id'), table_name='search_events')
    op.drop_index(op.f('ix_search_events_query_text'), table_name='search_events')
    op.drop_index(op.f('ix_search_events_id'), table_name='search_events')
    op.drop_index(op.f('ix_search_events_created_at'), table_name='search_events')
    op.drop_table('search_events')
    op.drop_index(op.f('ix_search_analytics_query'), table_name='search_analytics')
    op.drop_index(op.f('ix_search_analytics_id'), table_name='search_analytics')
    op.drop_index(op.f('ix_search_analytics_created_at'), table_name='search_analytics')
    op.drop_table('search_analytics')
    op.drop_index(op.f('ix_resumes_id'), table_name='resumes')
    op.drop_table('resumes')
    op.drop_index(op.f('ix_resume_profiles_id'), table_name='resume_profiles')
    op.drop_table('resume_profiles')
    op.drop_index(op.f('ix_resume_match_results_user_id'), table_name='resume_match_results')
    op.drop_index(op.f('ix_resume_match_results_opportunity_id'), table_name='resume_match_results')
    op.drop_index(op.f('ix_resume_match_results_id'), table_name='resume_match_results')
    op.drop_table('resume_match_results')
    op.drop_index(op.f('ix_opportunity_sources_id'), table_name='opportunity_sources')
    op.drop_table('opportunity_sources')
    op.drop_index(op.f('ix_opportunity_history_severity'), table_name='opportunity_history')
    op.drop_index(op.f('ix_opportunity_history_recorded_at'), table_name='opportunity_history')
    op.drop_index(op.f('ix_opportunity_history_opportunity_id'), table_name='opportunity_history')
    op.drop_index(op.f('ix_opportunity_history_id'), table_name='opportunity_history')
    op.drop_index(op.f('ix_opportunity_history_event_type'), table_name='opportunity_history')
    op.drop_index(op.f('ix_opportunity_history_changed_field'), table_name='opportunity_history')
    op.drop_table('opportunity_history')
    op.drop_index(op.f('ix_job_quality_metrics_id'), table_name='job_quality_metrics')
    op.drop_table('job_quality_metrics')
    op.drop_index(op.f('ix_job_match_scores_id'), table_name='job_match_scores')
    op.drop_table('job_match_scores')
    op.drop_index(op.f('ix_collection_lineage_id'), table_name='collection_lineage')
    op.drop_table('collection_lineage')
    op.drop_index(op.f('ix_career_readiness_snapshots_user_id'), table_name='career_readiness_snapshots')
    op.drop_index(op.f('ix_career_readiness_snapshots_target_role'), table_name='career_readiness_snapshots')
    op.drop_index(op.f('ix_career_readiness_snapshots_id'), table_name='career_readiness_snapshots')
    op.drop_table('career_readiness_snapshots')
    op.drop_index(op.f('ix_career_readiness_user_id'), table_name='career_readiness')
    op.drop_index(op.f('ix_career_readiness_target_role'), table_name='career_readiness')
    op.drop_index(op.f('ix_career_readiness_id'), table_name='career_readiness')
    op.drop_table('career_readiness')
    op.drop_index(op.f('ix_applications_id'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_users_verification_token'), table_name='users')
    op.drop_index(op.f('ix_users_reset_token'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_search_aggregates_query_text'), table_name='search_aggregates')
    op.drop_index(op.f('ix_search_aggregates_last_searched_at'), table_name='search_aggregates')
    op.drop_index(op.f('ix_search_aggregates_id'), table_name='search_aggregates')
    op.drop_table('search_aggregates')
    op.drop_index(op.f('ix_role_skill_maps_skill'), table_name='role_skill_maps')
    op.drop_index(op.f('ix_role_skill_maps_role'), table_name='role_skill_maps')
    op.drop_index(op.f('ix_role_skill_maps_id'), table_name='role_skill_maps')
    op.drop_table('role_skill_maps')
    op.drop_index(op.f('ix_raw_jobs_id'), table_name='raw_jobs')
    op.drop_table('raw_jobs')
    op.drop_index(op.f('ix_raw_internships_id'), table_name='raw_internships')
    op.drop_table('raw_internships')
    op.drop_index(op.f('ix_pipeline_runs_pipeline_name'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_id'), table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    op.drop_index(op.f('ix_opportunities_title'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_opportunity_hash'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_opportunity_category'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_location'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_link_quality_score'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_lifecycle_status'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_legacy_hash'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_last_verified_at'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_is_india_job'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_india_relevance_score'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_india_confidence_score'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_confidence_score'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_computed_rank_score'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_completeness_score'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_company'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_change_score'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_apply_url_status'), table_name='opportunities')
    op.drop_table('opportunities')
    op.drop_index(op.f('ix_normalized_locations_raw_value'), table_name='normalized_locations')
    op.drop_index(op.f('ix_normalized_locations_id'), table_name='normalized_locations')
    op.drop_index(op.f('ix_normalized_locations_city'), table_name='normalized_locations')
    op.drop_table('normalized_locations')
    op.drop_index(op.f('ix_learning_resources_id'), table_name='learning_resources')
    op.drop_table('learning_resources')
    op.drop_index(op.f('ix_job_sources_success_count'), table_name='job_sources')
    op.drop_index(op.f('ix_job_sources_source_name'), table_name='job_sources')
    op.drop_index(op.f('ix_job_sources_id'), table_name='job_sources')
    op.drop_index(op.f('ix_job_sources_health_score'), table_name='job_sources')
    op.drop_table('job_sources')
    op.drop_index(op.f('ix_hiring_intelligence_global_snapshots_snapshot_date'), table_name='hiring_intelligence_global_snapshots')
    op.drop_index(op.f('ix_hiring_intelligence_global_snapshots_id'), table_name='hiring_intelligence_global_snapshots')
    op.drop_table('hiring_intelligence_global_snapshots')
    op.drop_index(op.f('ix_hiring_intelligence_company_snapshots_snapshot_date'), table_name='hiring_intelligence_company_snapshots')
    op.drop_index(op.f('ix_hiring_intelligence_company_snapshots_id'), table_name='hiring_intelligence_company_snapshots')
    op.drop_index(op.f('ix_hiring_intelligence_company_snapshots_company_name'), table_name='hiring_intelligence_company_snapshots')
    op.drop_table('hiring_intelligence_company_snapshots')
    op.drop_index(op.f('ix_discovered_company_ats_id'), table_name='discovered_company_ats')
    op.drop_index(op.f('ix_discovered_company_ats_company_name'), table_name='discovered_company_ats')
    op.drop_table('discovered_company_ats')
    op.drop_index(op.f('ix_dashboard_stats_cache_id'), table_name='dashboard_stats_cache')
    op.drop_table('dashboard_stats_cache')
    op.drop_index(op.f('ix_company_registry_id'), table_name='company_registry')
    op.drop_index(op.f('ix_company_registry_company_name'), table_name='company_registry')
    op.drop_table('company_registry')
    op.drop_index(op.f('ix_collector_health_history_snapshot_date'), table_name='collector_health_history')
    op.drop_index(op.f('ix_collector_health_history_id'), table_name='collector_health_history')
    op.drop_index(op.f('ix_collector_health_history_collector_name'), table_name='collector_health_history')
    op.drop_table('collector_health_history')
    op.drop_index(op.f('ix_collector_health_roi_tier'), table_name='collector_health')
    op.drop_index(op.f('ix_collector_health_id'), table_name='collector_health')
    op.drop_index(op.f('ix_collector_health_collector_score'), table_name='collector_health')
    op.drop_index(op.f('ix_collector_health_collector_name'), table_name='collector_health')
    op.drop_index(op.f('ix_collector_health_ats_type'), table_name='collector_health')
    op.drop_table('collector_health')
    op.drop_index(op.f('ix_collector_failures_id'), table_name='collector_failures')
    op.drop_index(op.f('ix_collector_failures_collector_name'), table_name='collector_failures')
    op.drop_table('collector_failures')
    op.drop_index(op.f('ix_collector_alerts_id'), table_name='collector_alerts')
    op.drop_index(op.f('ix_collector_alerts_created_at'), table_name='collector_alerts')
    op.drop_index(op.f('ix_collector_alerts_collector_name'), table_name='collector_alerts')
    op.drop_index(op.f('ix_collector_alerts_alert_type'), table_name='collector_alerts')
    op.drop_table('collector_alerts')
    op.drop_index(op.f('ix_certifications_id'), table_name='certifications')
    op.drop_table('certifications')
    op.drop_index(op.f('ix_career_insights_id'), table_name='career_insights')
    op.drop_table('career_insights')
    op.drop_index(op.f('ix_ats_health_log_id'), table_name='ats_health_log')
    op.drop_index(op.f('ix_ats_health_log_company_name'), table_name='ats_health_log')
    op.drop_table('ats_health_log')
    # ### end Alembic commands ###
