"""Phase_11_3_8_Lifecycle_Metadata

Revision ID: 8ed26c9152c4
Revises: 08a47448b137
Create Date: 2026-07-31 15:03:40.367350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ed26c9152c4'
down_revision: Union[str, None] = '08a47448b137'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('learning_resources', sa.Column('status', sa.String(), nullable=True))
    op.add_column('opportunities', sa.Column('published_at', sa.DateTime(), nullable=True))
    op.add_column('opportunities', sa.Column('expires_at', sa.DateTime(), nullable=True))
    op.add_column('opportunities', sa.Column('data_origin', sa.String(), nullable=True))
    op.add_column('opportunities', sa.Column('source_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('opportunities', 'source_type')
    op.drop_column('opportunities', 'data_origin')
    op.drop_column('opportunities', 'expires_at')
    op.drop_column('opportunities', 'published_at')
    op.drop_column('learning_resources', 'status')
    # ### end Alembic commands ###
