from typing import List, Dict, Any
from ..base_collector import BaseCollector

class CertificateCollector(BaseCollector):
    @property
    def source_name(self) -> str:
        return "Official Certifications Directory"

    def collect(self) -> List[Dict[str, Any]]:
        certifications = [
            {
                "name": "AWS Certified Data Engineer - Associate",
                "provider": "Amazon Web Services (AWS)",
                "category": "Certification",
                "description": "Validates expertise in core data-related AWS services, implementing data pipelines, monitoring and troubleshooting issues, and optimizing cost and performance.",
                "url": "https://aws.amazon.com/certification/certified-data-engineer-associate/",
                "difficulty": "Intermediate",
                "duration": "130 minutes (Exam)",
                "is_free": False,
                "skills_covered": ["AWS", "Data Engineering", "Data Pipelines", "Redshift", "Glue", "Athena"],
                "roles": ["Data Engineer"],
                "source": self.source_name,
                "is_processed": False,
                "cost": "$150",
                "estimated_hours": 60,
                "validity_years": 3,
                "exam_required": True
            },
            {
                "name": "Microsoft Certified: Azure Data Engineer Associate",
                "provider": "Microsoft",
                "category": "Certification",
                "description": "Subject matter expertise integrating, transforming, and consolidating data from various structured and unstructured data systems into structures that are suitable for building analytics solutions.",
                "url": "https://learn.microsoft.com/en-us/credentials/certifications/azure-data-engineer/",
                "difficulty": "Intermediate",
                "duration": "120 minutes (Exam)",
                "is_free": False,
                "skills_covered": ["Azure", "Data Engineering", "Synapse Analytics", "Data Factory", "Databricks"],
                "roles": ["Data Engineer"],
                "source": self.source_name,
                "is_processed": False,
                "cost": "$165",
                "estimated_hours": 80,
                "validity_years": 1,
                "exam_required": True
            },
            {
                "name": "Microsoft Certified: Power BI Data Analyst Associate",
                "provider": "Microsoft",
                "category": "Certification",
                "description": "Candidates design and build scalable data models, clean and transform data, and enable advanced analytic capabilities that provide meaningful business value through easy-to-comprehend data visualizations.",
                "url": "https://learn.microsoft.com/en-us/credentials/certifications/data-analyst-associate/",
                "difficulty": "Intermediate",
                "duration": "100 minutes (Exam)",
                "is_free": False,
                "skills_covered": ["Power BI", "Data Visualization", "Data Modeling", "DAX", "Data Analysis"],
                "roles": ["Data Analyst", "Business Analyst"],
                "source": self.source_name,
                "is_processed": False,
                "cost": "$165",
                "estimated_hours": 50,
                "validity_years": 1,
                "exam_required": True
            },
            {
                "name": "Google Data Analytics Professional Certificate",
                "provider": "Google",
                "category": "Certification",
                "description": "Get professional training designed by Google and have the opportunity to connect with top employers. Prepare for a new career in the high-growth field of data analytics.",
                "url": "https://grow.google/certificates/data-analytics/",
                "difficulty": "Beginner",
                "duration": "6 months",
                "is_free": False,
                "skills_covered": ["Data Analysis", "SQL", "R", "Tableau", "Data Visualization", "Spreadsheets"],
                "roles": ["Data Analyst", "Business Analyst"],
                "source": self.source_name,
                "is_processed": False,
                "cost": "Coursera Subscription",
                "estimated_hours": 180,
                "validity_years": 0,
                "exam_required": False
            },
            {
                "name": "Databricks Certified Data Engineer Associate",
                "provider": "Databricks",
                "category": "Certification",
                "description": "Assesses the ability to use the Databricks Lakehouse Platform to perform introductory data engineering tasks, including building basic ETL pipelines.",
                "url": "https://www.databricks.com/learn/certification/data-engineer-associate",
                "difficulty": "Intermediate",
                "duration": "90 minutes (Exam)",
                "is_free": False,
                "skills_covered": ["Databricks", "Apache Spark", "Delta Lake", "Data Engineering", "Python", "SQL"],
                "roles": ["Data Engineer"],
                "source": self.source_name,
                "is_processed": False,
                "cost": "$200",
                "estimated_hours": 40,
                "validity_years": 2,
                "exam_required": True
            },
            {
                "name": "SnowPro Core Certification",
                "provider": "Snowflake",
                "category": "Certification",
                "description": "Demonstrates an individual's knowledge to apply specific core expertise implementing and migrating to Snowflake. Covers architecture, data loading, and performance.",
                "url": "https://www.snowflake.com/en/resources/learn/training-certification/snowpro-core-certification/",
                "difficulty": "Intermediate",
                "duration": "115 minutes (Exam)",
                "is_free": False,
                "skills_covered": ["Snowflake", "Data Warehousing", "SQL", "Cloud Data Platform", "Data Pipelines"],
                "roles": ["Data Engineer", "Data Analyst"],
                "source": self.source_name,
                "is_processed": False,
                "cost": "$175",
                "estimated_hours": 60,
                "validity_years": 2,
                "exam_required": True
            },
            {
                "name": "Professional Data Engineer",
                "provider": "Google Cloud (GCP)",
                "category": "Certification",
                "description": "A Professional Data Engineer makes data useful and highly accessible for others. They design, build, operationalize, secure, and monitor data processing systems.",
                "url": "https://cloud.google.com/learn/certification/data-engineer",
                "difficulty": "Advanced",
                "duration": "120 minutes (Exam)",
                "is_free": False,
                "skills_covered": ["GCP", "BigQuery", "Dataflow", "Dataproc", "Data Engineering", "Machine Learning"],
                "roles": ["Data Engineer"],
                "source": self.source_name,
                "is_processed": False,
                "cost": "$200",
                "estimated_hours": 100,
                "validity_years": 2,
                "exam_required": True
            },
            {
                "name": "IIBA Entry Certificate in Business Analysis (ECBA)",
                "provider": "IIBA",
                "category": "Certification",
                "description": "Recognizes individuals ready to develop their business analysis skills, knowledge and behaviors as practicing business analysis professionals.",
                "url": "https://www.iiba.org/business-analysis-certifications/ecba/",
                "difficulty": "Beginner",
                "duration": "1.5 Hours (Exam)",
                "is_free": False,
                "skills_covered": ["Business Analysis", "Requirements Analysis", "Process Analysis", "BABOK"],
                "roles": ["Business Analyst"],
                "source": self.source_name,
                "is_processed": False,
                "cost": "$195 - $350",
                "estimated_hours": 21,
                "validity_years": 0,
                "exam_required": True
            }
        ]
        return certifications
